apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: amitm
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32324
  selector:
    app: nginx
  type: NodePort
